package main

import (
	"github.com/amazon-import-export-snowball/mcp-server/config"
	"github.com/amazon-import-export-snowball/mcp-server/models"
	tools_x_amz_target_awsiesnowballjobmanagementservice_describeaddress "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_describeaddress"
	tools_x_amz_target_awsiesnowballjobmanagementservice_listclusters "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_listclusters"
	tools_x_amz_target_awsiesnowballjobmanagementservice_describeaddresses "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_describeaddresses"
	tools_x_amz_target_awsiesnowballjobmanagementservice_listjobs "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_listjobs"
	tools_x_amz_target_awsiesnowballjobmanagementservice_listcompatibleimages "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_listcompatibleimages"
	tools_x_amz_target_awsiesnowballjobmanagementservice_updatecluster "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_updatecluster"
	tools_x_amz_target_awsiesnowballjobmanagementservice_updatelongtermpricing "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_updatelongtermpricing"
	tools_x_amz_target_awsiesnowballjobmanagementservice_createjob "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_createjob"
	tools_x_amz_target_awsiesnowballjobmanagementservice_describereturnshippinglabel "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_describereturnshippinglabel"
	tools_x_amz_target_awsiesnowballjobmanagementservice_createlongtermpricing "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_createlongtermpricing"
	tools_x_amz_target_awsiesnowballjobmanagementservice_createreturnshippinglabel "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_createreturnshippinglabel"
	tools_x_amz_target_awsiesnowballjobmanagementservice_describejob "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_describejob"
	tools_x_amz_target_awsiesnowballjobmanagementservice_getjobunlockcode "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_getjobunlockcode"
	tools_x_amz_target_awsiesnowballjobmanagementservice_getsnowballusage "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_getsnowballusage"
	tools_x_amz_target_awsiesnowballjobmanagementservice_listpickuplocations "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_listpickuplocations"
	tools_x_amz_target_awsiesnowballjobmanagementservice_updatejob "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_updatejob"
	tools_x_amz_target_awsiesnowballjobmanagementservice_listclusterjobs "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_listclusterjobs"
	tools_x_amz_target_awsiesnowballjobmanagementservice_createaddress "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_createaddress"
	tools_x_amz_target_awsiesnowballjobmanagementservice_listlongtermpricing "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_listlongtermpricing"
	tools_x_amz_target_awsiesnowballjobmanagementservice_updatejobshipmentstate "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_updatejobshipmentstate"
	tools_x_amz_target_awsiesnowballjobmanagementservice_describecluster "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_describecluster"
	tools_x_amz_target_awsiesnowballjobmanagementservice_getsoftwareupdates "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_getsoftwareupdates"
	tools_x_amz_target_awsiesnowballjobmanagementservice_cancelcluster "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_cancelcluster"
	tools_x_amz_target_awsiesnowballjobmanagementservice_createcluster "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_createcluster"
	tools_x_amz_target_awsiesnowballjobmanagementservice_listserviceversions "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_listserviceversions"
	tools_x_amz_target_awsiesnowballjobmanagementservice_getjobmanifest "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_getjobmanifest"
	tools_x_amz_target_awsiesnowballjobmanagementservice_canceljob "github.com/amazon-import-export-snowball/mcp-server/tools/x_amz_target_awsiesnowballjobmanagementservice_canceljob"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_x_amz_target_awsiesnowballjobmanagementservice_describeaddress.CreateDescribeaddressTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_listclusters.CreateListclustersTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_describeaddresses.CreateDescribeaddressesTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_listjobs.CreateListjobsTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_listcompatibleimages.CreateListcompatibleimagesTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_updatecluster.CreateUpdateclusterTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_updatelongtermpricing.CreateUpdatelongtermpricingTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_createjob.CreateCreatejobTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_describereturnshippinglabel.CreateDescribereturnshippinglabelTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_createlongtermpricing.CreateCreatelongtermpricingTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_createreturnshippinglabel.CreateCreatereturnshippinglabelTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_describejob.CreateDescribejobTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_getjobunlockcode.CreateGetjobunlockcodeTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_getsnowballusage.CreateGetsnowballusageTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_listpickuplocations.CreateListpickuplocationsTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_updatejob.CreateUpdatejobTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_listclusterjobs.CreateListclusterjobsTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_createaddress.CreateCreateaddressTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_listlongtermpricing.CreateListlongtermpricingTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_updatejobshipmentstate.CreateUpdatejobshipmentstateTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_describecluster.CreateDescribeclusterTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_getsoftwareupdates.CreateGetsoftwareupdatesTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_cancelcluster.CreateCancelclusterTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_createcluster.CreateCreateclusterTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_listserviceversions.CreateListserviceversionsTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_getjobmanifest.CreateGetjobmanifestTool(cfg),
		tools_x_amz_target_awsiesnowballjobmanagementservice_canceljob.CreateCanceljobTool(cfg),
	}
}
